<?php
  
  function share_selected_page_attachments(array &$attachments) {
      // Get share_selected configs.
      $config = \Drupal::config('share_selected.settings');
      // Get default settings.
      $default_settings = \Drupal\share_selected\Form\ShareSeletectedSettings::defaultSettings();
      $keys = array_keys($default_settings);
      foreach ($keys as $key) {
        $settings[$key] = is_null($config->get($key)) ? $default_settings[$key] : $config->get($key);
      }
      $attachments['#attached']['drupalSettings']['share_selected'] = [];
      $attachments['#attached']['drupalSettings']['share_selected']['settings'] = $settings;
      $attachments['#attached']['library'][] = 'share_selected/share';
    }
