share_selected.settings:
  type: config_object
  label: 'Share Selected settings'
  mapping:
    facebook:
      type: boolean
      label: 'Enable facebook'
    twiiter:
      type: boolean
      label: 'Enable Twitter'
    twiiter_username:
      type: string
      label: 'Twitter username'
    bg_color:
      type: string
      label: 'Background Color'

